{% set version = "2.1.8" %}

package:
  name: scikit-ued
  version: {{ version }}

source:
  fn: scikit-ued-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/s/scikit-ued/scikit-ued-{{ version }}.tar.gz
  sha256: 0ea935631b8af47a6488abdd2bbb6d3abe900bf99a95efe7f292f5e8be9a6d90

build:
  noarch: python
  number: 0
  entry_points:
    - skued = skued.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy >=1.17, <2
    - scipy >=1.5.0, <2
    - scikit-image >=0.17, <1
    - pywavelets >=1.0.0, <2
    - crystals >=1.3.0, <2
    - npstreams >=1.6.5, <2
    - pyyaml >=3.1
    - matplotlib-base >=3.0.0, <4

test:
  requires:
    - pytest >= 6
  imports:
    - skued
  commands:
    - skued --help
    - pytest --pyargs skued

about:
  home: https://github.com/LaurentRDC/scikit-ued
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Collection of algorithms and functions for ultrafast electron diffraction
  description: Collection of algorithms and functions for ultrafast electron diffraction.
  doc_url: https://scikit-ued.readthedocs.io/
  dev_url: https://github.com/LaurentRDC/scikit-ued

extra:
  recipe-maintainers:
    - LaurentRDC
