{% set version = "2.0.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "c04f9b91e2c1e67cebf124c77238fe532925ed3db7a5522b5710cf15fa6c3e2d" %}

package:
  name: 'scikit-ued'
  version: '{{ version }}'

source:
  fn: 'scikit-ued-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/s/scikit-ued/scikit-ued-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - python>=3.6
  run:
    - python>=3.6
    - numpy>=1.13, <2
    - scipy>=1.0.0, <2
    - scikit-image>=0.15, <1
    - tifffile>=0.13,<1
    - pywavelets>=1.0.0,<2
    - crystals>=0.6.5,<1
    - npstreams>=1.6,<2
    - pyyaml>=3.1,<4

test:
  imports:
    - skued

about:
  home: https://github.com/LaurentRDC/scikit-ued
  license: MIT
  license_family: MIT
  license_file: 'LICENSE.txt'
  summary: Collection of algorithms and functions for ultrafast electron diffraction
  description: Collection of algorithms and functions for ultrafast electron diffraction.
  doc_url: https://scikit-ued.readthedocs.io/
  dev_url: 'https://github.com/LaurentRDC/scikit-ued'

extra:
  recipe-maintainers: 
    - LaurentRDC
