{% set version = "2.1.0" %}
{% set hash_type = "sha256" %}
{% set hash_value = "77116a087b6bc0916033874dcd498ea20177d148d31c0c1e18b20d9b351c9790" %}

package:
  name: 'scikit-ued'
  version: '{{ version }}'

source:
  fn: 'scikit-ued-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/s/scikit-ued/scikit-ued-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  noarch: python
  number: 0
  entry_points:
    - skued = skued.__main__:main
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - numpy >=1.15, <2
    - scipy >=1.0.0, <2
    - scikit-image >=0.17, <1
    - pywavelets >=1.0.0, <2
    - crystals >=1.2.2, <2
    - npstreams >=1.6.4, <2
    - pyyaml >=3.1
    - matplotlib-base >=3.0.0, <4

test:
  requires:
    - pytest >= 6
  imports:
    - skued
  commands:
    - skued --help
    - pytest --pyargs skued

about:
  home: https://github.com/LaurentRDC/scikit-ued
  license: GPL-3.0-only
  license_family: GPL3
  license_file: 'LICENSE.txt'
  summary: Collection of algorithms and functions for ultrafast electron diffraction
  description: Collection of algorithms and functions for ultrafast electron diffraction.
  doc_url: https://scikit-ued.readthedocs.io/
  dev_url: 'https://github.com/LaurentRDC/scikit-ued'

extra:
  recipe-maintainers: 
    - LaurentRDC
