travis:
  secure:
    BINSTAR_TOKEN: wvRb6PFI9rogtFYDwdKf1zlxEjoxbOOPPfxyTQaud1eWJGe+qiuUHE+yTV0t7sPvkLbrPD0eDVqzL4hJkPp6WulTzGaowP6k0oTNWOjquVrOQOzwUWPZhyefxj/4ziy9cv1YPijWYO38b1MeJ5d7xF5R8ybEsMBzDELWucU1ydC1yB0brqCbtdBJAr/WKQQVRCQiCkpXT/L0OupnKN/E9MujUZdrbuiRKydtnIAmBiNstVLySU6QxbNlST3o+AWTe5jOqUy1tJUaBbibPUhIHYtG1JVw3uID1WewPxHhu3jw2hJ+aQetnkujhQ+PUTtP6uRDjDCy+xznshwVFr/eO1adDbkQR+n8NzgxZYR6wpuBTl3P6/NuWAooQF8qNukKu7okbeG4J89sTcKjxr743Vg9KMbHSLxHICyVh9IJf9SyJRBfYiqcpU072zBSroRNMlSLn4GJTMwWY+g2DWHju1ESl7eCgoeNRY82xIA2SL0NTatOYerjrNw/vfHsa590KmfPQbdNHxT8dPkb25WzZP719rC0kcJeg+G6tS2jXeNx3YXZpAoERaXJ2sUlyzvoPS5IKT8zJh8zOPuETZU3UJiqrLnUfdRmoOlogKuQgrkZd6KZdCR8+izp1ArBIz9090hshnwrklVWAOfsQkRfbWvY8tF5VPIcMXCHGs08yVE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
