travis:
  secure:
    BINSTAR_TOKEN: nJT3o3SkiJtyoSrLZ39TTvDHIBJb/iaQ6h7tlG4cmNnJB5Bq2zg00e0w3zP7ZEZW2YbzzLKkIwIAf50btbmtYCoUPb90/Ag3qI24spOVWRYpAPs/MvzWfteTL5aLcDmLHjN9KIWJlsR4TNgrgmvX3hm/Qifky/EoAKah+pBZGuUSzRZPSqxyZ/bw8S3wh6mKEw9BrOG+1HXgXqNmnnLiB5DeoMdE4sW/xkDfeMV4xjN4/94oOecySRSxU2xF00XMBWat6hqBxqfICuySJjc0yhO7/BDf4UoXM+JG65vyKcK5coMXpp37htHddCIQVGSjJnw+OiusOn3dN14ONzTKmq33hPFo4Zr5RcUmUjQkM1LcVgbpjYgD6RRWaCZ/jlX8frPKWxSgLs7Up9EwnNUJNSIpR3yq9HESX6eYCnMR04NxyJCwfUUis7qTOLAhn6K0FjkX0bNlibYC2fwb5DFpXvaVpdZozLgG+7FMlo7x//ffCrQBjw+Qf0WApYc03lsIIAgFh4EUpCTEQrg+Wz5b0B2Mo37Hy85wr26kUNYH2QyeTzTNdnesst0ePMI2WcjjtBzAUnHNUQAed/BDzSF8uWHTWLynTxb04GR0KvZpFPtxtrINbfqthW753ETvESnpEq3lb82cVQa6qO+L6Iu8IV8hgdTMZRwjbfDe5ebMt5Q=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
