travis:
  secure:
    BINSTAR_TOKEN: BthJX77+nn0Cz+MmOtuRPV5djqs1p5eWMmPMppMgKWm3IP1bDyuRbqttFDg2mjsEW68Lhfk7bjYa0CPR5RrwVS+r7LnYLEviMEZL+BPeu7LhUlP9lG2Nv0HRIdYt2Mqytl8D9TavxJ+NTyLvVJkfK/8PJG00giUdPYciNL9sLQ96VgRz+caAIkAjlghk9PaP+SDiaHrXRqLnq/9SCHOpXZWr4P0PaKGFoNqC4Zdfcc0S4ts9ZMa+Fgdp2dekK2X1KbuR0bo+NudcJkfJRlEwVcCP552v/Udm6y88wAJs1onQjRAMuubCe+Zbi4cZ2j21INASFL+EoX5NnfopiSmMU9HuzzODLDrjRgSg0iRed27TxDVDZCd9dzIG/Oci6vf3cDsZPI8Pn4amYafKUrwWBBlaXdTd+LsHFsSM5RscLOBmJFKdUru3lbZdjYqoWavYbRcmU8+DJONUHzYrYNT6FfX4PwwDOdn4peBK8dbV9r4Deu7ldjUK6DheinRYBEVAesl/baWaesJVeZF9+XxAUv6FeYcvmeeS5UECxrb1mgcyjphPGdMlPXrlAFMEHtPMG/JHTdpxtWCtbVTQoPlCprCEYgfF9l3jSItnnAShiXVvYaPuYMdQKCHwGr/YmYGBSTrVEMdfT1SLW2MujN5li59ldfpJftE74A0lhtZICA0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
